### PR TITLE
Fix with ref request

### PR DESCRIPTION
**Pull request by MIchaelMainer**
Fixes issue introduced with #131 

Was causing the following issue at generation time.
```
11:25:29 Microsoft.Graph.ODataTemplateWriter.TemplateProcessor.TemplateProcessor Error(0): d:\repos\MSGraph-SDK-Code-Generator\Templates\CSharp\Requests\IEntityWithReferenceRequest.cs.tt(22,64) : error CS1501: No overload for method 'GetEntityGetAsyncMethod' takes 2 arguments
11:25:30 Microsoft.Graph.ODataTemplateWriter.TemplateProcessor.TemplateProcessor Error(1): d:\repos\MSGraph-SDK-Code-Generator\Templates\CSharp\Requests\IEntityWithReferenceRequest.cs.tt(24,64) : error CS1501: No overload for method 'GetEntityCreateAsyncMethod' takes 2 arguments
11:25:30 Microsoft.Graph.ODataTemplateWriter.TemplateProcessor.TemplateProcessor Error(2): d:\repos\MSGraph-SDK-Code-Generator\Templates\CSharp\Requests\IEntityWithReferenceRequest.cs.tt(26,64) : error CS1501: No overload for method 'GetEntityUpdateAsyncMethod' takes 2 arguments
11:25:30 VIPR System.InvalidOperationException: Template error.
   at ........
```

### CODE REVIEW

**Comment by MIchaelMainer** [comment]
@microsoftgraph/sdk-reviewers Whenever we have changes to a template in one language, we always need to investigate whether we need to make a similar change for the templates for the other platforms. So in this case, @deepak2016 the same issue doesn't appear to be present in the Android or Java templates. With that said, we typically want to generate after a template change to understand the impact on the generated file set.
